# Generated by Django 4.0.5 on 2022-06-07 09:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Opinion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000)),
                ('content', models.CharField(max_length=10000)),
                ('who', models.CharField(max_length=50)),
                ('student_number', models.IntegerField()),
                ('date_added', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='TimeLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=10000)),
                ('content', models.CharField(max_length=10000)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('opinion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='meyasubako.opinion')),
            ],
        ),
    ]
