# Generated by Django 4.1 on 2022-09-14 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meyasubako', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opinion',
            name='student_number',
        ),
        migrations.AddField(
            model_name='opinion',
            name='student_email',
            field=models.CharField(default='example@email.com', max_length=50),
        ),
    ]
