# Generated by Django 4.0.5 on 2022-06-07 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meyasubako', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='content',
            field=models.CharField(max_length=10000, null=True),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='student_number',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='who',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
