# Generated by Django 4.0.5 on 2022-06-12 04:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meyasubako', '0002_alter_opinion_content_alter_opinion_student_number_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opinion',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='content',
            field=models.CharField(default='プペ', max_length=10000),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='student_number',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='title',
            field=models.CharField(default='プペ', max_length=10000),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='who',
            field=models.CharField(default='プペ', max_length=50),
        ),
    ]
