# Generated by Django 4.1 on 2022-09-24 00:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meyasubako', '0002_remove_opinion_student_number_opinion_student_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='student_email',
            field=models.CharField(default='example@gmail.com', max_length=255),
        ),
    ]
