# Generated by Django 4.0.5 on 2022-06-12 04:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meyasubako', '0003_opinion_status_alter_opinion_content_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='title',
            field=models.CharField(default='プペ', max_length=16),
        ),
    ]
