# Generated by Django 4.0.5 on 2022-06-12 05:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('meyasubako', '0004_alter_opinion_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opinion',
            name='content',
            field=models.CharField(max_length=10000),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='student_number',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='title',
            field=models.CharField(max_length=16),
        ),
        migrations.AlterField(
            model_name='opinion',
            name='who',
            field=models.CharField(max_length=50),
        ),
    ]
